export const Icons = {
  arrowDownRight: {
    name: "ArrowDownRight",
    class: "size-3 ml-0.5",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "2.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  chevronRight: {
    name:"ChevronRight",
    class:
    "size-4 shrink-0 transition duration-300 ease-in-out group-hover:translate-x-1",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "2.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  cursorRays: {
    name:"MousePointerClick",
    class: "size-6 text-slate-500",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  cog: {
    name:"Settings",
    class: "size-6 text-slate-500",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  puzzle: {
    name:"Puzzle",
    class: "size-6 text-slate-500",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  dataBase: {
    name:"Database",
    class: "size-6 text-slate-600",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  brain: {
    name:"Brain",
    class: "size-6 text-slate-600",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  lightbulb: {
    name:"Lightbulb",
    class: "size-6 text-slate-600",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  chartPie: {
    name:"ChartPie",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  portfolio: {
    name:"BriefcaseBusiness",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  presentationChart: {
    name:"Presentation",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  articles: {
    name:"Newspaper",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  documentChartBar: {
    name:"ChartBar",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  blankDocument: {
    name:"File",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  documentMagnifyingGlass: {
    name:"FileSearch",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  info: {
    name:"Info",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  mobile: {
    name:"Smartphone",
    class: "size-4",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  email: {
    name:"Mail",
    class: "size-4",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  world: {
    name:"Globe",
    class: "size-4",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },

  mapPin: {
    name:"MapPin",
    class: "shrink-0 size-6 text-slate-600",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  download: {
    name:"Download",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  badge: {
    name:"BadgeCheck",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  chatBubble: {
    name:"MessageSquareMore",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  arrowPath: {
    name:"RefreshCcw",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  check: {
    name:"Check",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  minus: {
    name:"Minus",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  questionMark: {
    name:"circle-help",
    class: "shrink-0 size-6 text-slate-400 mt-0.5",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  checkCircle: {
    name:"CircleCheck",
    class: "shrink-0 size-6 text-teal-600",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  newWindow: {
    name:"AppWindowMac",
    class: "shrink-0",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  thumbUp: {
    name:"ThumbsUp",
    class: "size-4 shrink-0",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "2",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
  thumbDown: {
    name:"ThumbsDown",
    class: "size-4 shrink-0",
    viewBox: "0 0 24 24",
    fill: "none",
    strokeWidth: "2",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    stroke: "currentColor",
  },
};
